### ISSUE TITLE
About resuming the training of pre-trained weights.

### ISSUE THREAD

**Issue by Bostoncake** [leokarlin/BrAD#5]
Hi! Sorry for bothering you again. I am trying to resume training from the checkpoints you released at `https://drive.google.com/file/d/1T7v2xwAWQGsAv11-CEwKLmUH-TmCkue9/view?usp=sharing` by using --resume parameters when running `main_brad.py`. However, I got the following errors:

> File "main_brad.py", line 179, in main_worker
>     missing_keys, unexpected_keys = model.load_state_dict(sd, strict=False)
>   File "/home/xxxxx/miniconda3/envs/brad/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1223, in load_state_dict
> Traceback (most recent call last):
>   File "main_brad.py", line 649, in <module>
>     raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
> RuntimeError: Error(s) in loading state_dict for DistributedDataParallel:
>         size mismatch for module.queue: copying a param with shape torch.Size([128, 65536]) from checkpoint, the shape in current model is torch.Size([128, 65088]).
>         size mismatch for module.queue_idx: copying a param with shape torch.Size([65536]) from checkpoint, the shape in current model is torch.Size([65088]).

I was using the default parameters in `config.py` and set `--nproc_per_node=4`. It seems that the model parameters ("65088" in "the shape in current model is torch.Size([65088])") vary as the batch size changes. I wonder what is the reason of this and I would sincerely appreciate it if you would provide the proper way to resume training the released weights.

Thank you!

**Comment by Bostoncake** [comment]
And I have another question. Is it necessary to train 300 epochs as in `config.py`? What is the time cost for training it from scratch? Thank you!

**Comment by JizeZhangPsych** [comment]
As for the first question, 65088=288\*2\*113 (where 288 is the default batch size in config.py), it's because this line of code in moco.builder.py:
```assert self.K % batch_size == 0, f'self.K={self.K}, batch_size={batch_size}'  # for simplicity```
and this two lines of code in config.py:
```real_bs = args.batch_size*2```
```args.moco_k -= (args.moco_k % real_bs)```
That is to say, as 65536 % (2*batch_size) = 113.78, the config.py change your self.K stealthly to 113\*576=65088.
And that's why batch size is limited for the code not to break and throwing an error.

However, this trick is not a necessity in code, and you can simply remove the two lines in config.py and change a little bit to the pointer part of dequeue and enqueue in builder.py and make the code run with any batch size.

**Comment by JizeZhangPsych** [comment]
As for the second question, you may need even more epochs in the UDG settings as it needs to pretrain for 1000 epochs from scratch lol.
For me in a server with 4\* RTX A5000, about 2 hours is needed for 1 epoch with the edge model, and less than 1 hour for 1 epoch with moco only. 
It seems that most of the time is consumed in the dataloader part after reading the images in, possibly either decompressing the jpeg file into tensors, or the simclr augmentation.
